### PR TITLE
Fix RangeError: Invalid array length

### LINKED ISSUE #529: RangeError: Invalid array length
Hello,

we sometimes get the Error `ERROR RangeError: Invalid array length` in our prod system. Sadly we could not reproduce it locally on our dev machine. 

The code the produces the error is this line:

`gridster.component.ts`

```ts
updateGrid(): void {
    if (this.$options.displayGrid === 'always' && !this.mobile) {
      this.renderer.addClass(this.el, 'display-grid');
    } else if (this.$options.displayGrid === 'onDrag&Resize' && this.dragInProgress) {
      this.renderer.addClass(this.el, 'display-grid');
    } else if (this.$options.displayGrid === 'none' || !this.dragInProgress || this.mobile) {
      this.renderer.removeClass(this.el, 'display-grid');
    }
    this.setGridDimensions();
    // error comes from next line
    this.gridColumns.length = Math.max(this.columns, Math.floor(this.curWidth / this.curColWidth)) || 0;
    this.gridRows.length = Math.max(this.rows, Math.floor(this.curHeight / this.curRowHeight)) || 0;
    this.cdRef.markForCheck();
  }
```

Maybe you can add some extra checks to prevent the array length to be invalid.

### PR DESCRIPTION
**Pull request by 4kochi**
Hopefully the final fix, since we still got the error.

So we have to ensure that the length is an integer. Not sure though if Math.floor() is correct or if Math.ceil() would be better

Closes #529

### CODE REVIEW

**Comment by Ajayithena** [comment]
Actually i am still facing the same error i am currently using v8.4.2 which supposed to have fixes for this problem but in my case its still there.

When I try to add more than one gridster-item on canvas only than this kind of error i am getting...
error

**Comment by Vasanthvivi** [comment]
Math.floor() works fine to me

**Comment by Ajayithena** [comment]
> Math.floor() works fine to me

Can you please elaborate where you have used Math.floor

**Comment by Ajayithena** [comment]
Ok, I found out this fix is in v9.0.1 and its working with angular 8

**Pull request merged**
