### PR TITLE
feat(options): custom load gridster item option added

### PR DESCRIPTION
**Pull request by rajratnamaitry**

### CODE REVIEW

**Comment by rajratnamaitry** [comment]
// home.component.ts
`@ViewChildren(GridsterItemComponent) gridsterItemsList: QueryList<GridsterItemComponent>`
// method to load gridster-item after calculating dynamic x,y coordinate of  new generated gridster-Item.
`loadItems(){
this.gridsterItemsList.forEach(item => {
        item.ngOnDestroy();
      });
  }`

**Comment by tiberiuzuld** [comment]
Hi @rajratnamaitry ,
I don't seem to understand this PR, maybe your PR is not complete/missing changes?

**Comment by rajratnamaitry** [comment]
This PR is for controlling the load of gridster-item component

Example code :

``` typescript
import { GridsterItemExtendComponent } from 'gridster-item-extend';
@ViewChildren(GridsterItemExtendComponent) gridstersItem : QueryList<GridsterItemExtendComponent>;

ngOnInit(): void {
  this.options = {
    /* Default value : false;
    * If customLoadItems is not given then it will work as normal 
    * gridster-item component
    * 
    * If customLoadItems is set to true then you can control the loading of
    * gridster-item-extend component
    */
    customLoadItems: true,
    ....
    minCols: 100,
    maxCols: 1000,
    minRows: 100,
    maxRows: 1000,
    ...
  }
}
ngAfterViewInit(){
    this.loadGridsterItem();
}
loadGridsterItem(){
  // child node list 
  this.gridsterItems.forEach(item=> {
    // call method to load gridster item
    item.loadCurrentGridsterItem()
  })
}
```

**Comment by tiberiuzuld** [comment]
I am sorry, I still don't get it...
What is the use case for this?
Why don't you extend the `gridsterItem.component.ts`  if you want to extend the functionality?
Example:
```ts
export class GridsterItemExtendComponent extends GridsterItemComponent {
     
  ngOnInit(): void {  // overidden
    // my custom logic
  }
}
```

```html
<gridster [options]="options">
  <gridster-item-extended [item]="item" *ngFor="let item of dashboard">
    <!-- your content here -->
  </gridster-item-extended>
</gridster>
```

**Comment by rajratnamaitry** [comment]
yes, I have already implemented this. https://www.npmjs.com/package/gridster-item-extend
now I can close this PR. Thank you

**Pull request closed without merging**
